#
# Running the playbooks in sequence
#

- name: Running the playbook setting the time zone
  ansible.builtin.import_playbook: set_timezone.yml
- name: Running the playbook installing docker etc
  ansible.builtin.import_playbook: setup_docker.yml
- name: Running the playbook installing portainer
  ansible.builtin.import_playbook: setup_portainer.yml
- name: Running the playbook installing watchtower
  ansible.builtin.import_playbook: setup_watchtower.yml
