# Description: This playbook installs the ripper.
- name: Install the DVD ripper
  hosts: ares
  become: true
  tasks:
    - name: Install public Docker Container from GitHub Container Registry
      community.docker.docker_container:
        name: ripper
        image: ghcr.io/wolfpaulus/pi-the-ripper:latest
        image_pull_secrets:
          - "{{ PAT_PiTheRipper }}"            
        labels:
          com.centurylinklabs.watchtower.enable: "true"
        state: started
        restart_policy: unless-stopped
        devices:
          - /dev/sr0:/dev/sr0:rwm
        privileged: true
        volumes:
          - /var/log:/var/log
        env:
          TZ: "{{ timezone }}"
          SMB_SERVER: "{{ samba_host }}"
          SMB_USER: "{{ samba_user }}"
          SMB_PASS: "{{ samba_pw }}"
