# Description: Install What’s Up Docker (WUD) to automatically update Docker containers
- name: Install WUD
  hosts: ares
  become: true
  vars:
    poll_interval: 600 # polling interval in seconds (10 minutes)
  tasks:
    - name: Install WUD
      community.docker.docker_container:
        name: wud
        image: ghcr.io/getwud/wud:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          TZ: "{{ timezone }}"
          WUD_WATCHER_LOCAL_CRON: "*/5 * * * *"
          WUD_WATCHER_LOCAL_WATCHALL: "true"
          

