# Purpose: Setup CNAMES for the tunnels.
# This will create AND map CNAMES to the tunnel IDs. 
# I.e., associates the CNAMES with host that will receive the traffic.
# It's not a problem, if the CNAMES already exist or are already mapped to the tunnel IDs.
# This playbook requires that cloudflared is installed on the hosts. So this playbook should be run after the setup_cloudflare.yml playbook.

- name: Setup CNAMES for the alpha tunnel.
  hosts: alpha
  become: true
  tasks:
    - name: Create CNAMES for the alpha tunnel. # put newest first
      ansible.builtin.shell: |
        cloudflared tunnel route dns "{{ tunnel_id }}" wordgame
        cloudflared tunnel route dns "{{ tunnel_id }}" dca
        cloudflared tunnel route dns "{{ tunnel_id }}" ssh-{{ hostname.split('.')[0] }}
        cloudflared tunnel route dns "{{ tunnel_id }}" {{ hostname.split('.')[0] }}
      register: my_output
      changed_when: my_output.rc != 0

- name: Setup CNAMES for the beta tunnel.
  hosts: beta
  become: true
  tasks:
    - name: Create CNAMES for the beta tunnel. # put newest first
      ansible.builtin.shell: |
        cloudflared tunnel route dns "{{ tunnel_id }}" mysql
        cloudflared tunnel route dns "{{ tunnel_id }}" ssh-{{ hostname.split('.')[0] }}
        cloudflared tunnel route dns "{{ tunnel_id }}" {{ hostname.split('.')[0] }}
      register: my_output
      changed_when: my_output.rc != 0

- name: Setup CNAMES for the apollo tunnel.
  hosts: apollo
  become: true
  tasks:
    - name: Create CNAMES for the apollo tunnel. # put newest first
      ansible.builtin.shell: |
        cloudflared tunnel route dns "{{ tunnel_id }}" ssh-{{ hostname.split('.')[0] }}.{{ domain }}
        cloudflared tunnel route dns "{{ tunnel_id }}" {{ hostname.split('.')[0] }}.{{ domain }}
      register: my_output
      changed_when: my_output.rc != 0

- name: Setup CNAMES for the artemis tunnel.
  hosts: artemis
  become: true
  tasks:
    - name: Create CNAMES for the artemis tunnel. # put newest first
      ansible.builtin.shell: |
        cloudflared tunnel route dns "{{ tunnel_id }}" mongo
        cloudflared tunnel route dns "{{ tunnel_id }}" mysql
        cloudflared tunnel route dns "{{ tunnel_id }}" ssh-{{ hostname.split('.')[0] }}
        cloudflared tunnel route dns "{{ tunnel_id }}" {{ hostname.split('.')[0] }}
      register: my_output
      changed_when: my_output.rc != 0