# Description: This playbook is used to install Portainer on the target host.
- name: Install Portainer
  hosts: m6
  become: "{{ ansible_become }}"
  tasks:
    - name: Install Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:lts
        docker_host: "{{ docker_host }}"
        labels:
          com.centurylinklabs.watchtower.enable: "true"
        state: started
        restart_policy: unless-stopped
        command:
          - --no-setup-token
        published_ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
