- name: Install docker
  hosts: all
  become: true
  vars:
    packages:
      - nano
      - wget
      - htop
  tasks:
    - name: Ensure packages are installed
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Setup docker user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Install Docker-Compose&Set Permission
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: "755"

    - name: Create Docker-Compose symlink
      ansible.builtin.command:
        cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        creates: /usr/bin/docker-compose

    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
