# Description: This playbook installs cloudflared, tunnel credentials, and certificates on the hosts.
# PLEASE NOTE: Before running this playbook, you need to have the following variables defined in your inventory file: 
# account_tag, cloudflared_pkg, tunnel_cert, tunnel_name, tunnel_id, and tunnel_secret.
# Credentials and certificates can easily be created on the `control host` and added to the playbooks/certificates folder for deployment. E.g.:
# - brew install cloudflared
# - cloudflared tunnel login
# - cp /Users/wolf/.cloudflared/cert.pem ./playbooks/certificates/gamma_tunnel.cert
# - cloudflared tunnel create gamma
# Check here for more details: https://wolfpaulus.com/flare
# Since setup_cnams.yml requires that cloudflared is installed on the hosts, this playbook should be run before the setup_cnames.yml playbook.
#
# PLEASE NOTE: It's OK if the last step , starting the tunnel' originally fails because no ingress rules have been defined yet.

- name: Install cloudflared
  hosts: all
  become: true
  tasks:
    - name: Download the cloudflared Linux package
      ansible.builtin.get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/{{ cloudflared_pkg }}
        dest: /tmp/{{ cloudflared_pkg }}
        mode: "0440"

    - name: Depackage cloudflared
      ansible.builtin.shell: |
        sudo dpkg -i /tmp/{{ cloudflared_pkg }}
        mkdir -p /etc/cloudflared/
      register: result
      changed_when: result.rc != 0

    - name: Copy the certificate file for cloudflared.
      ansible.builtin.copy:
        src: "{{ tunnel_cert }}"
        dest: "/etc/cloudflared/cert.pem"
        mode: "0440"

    - name: Create the credentials file for cloudflared.
      ansible.builtin.copy:
        dest: "/etc/cloudflared/cred.json"
        content: |
          {
            "AccountTag"   : "{{ account_tag | quote }}",
            "TunnelID"     : "{{ tunnel_id | quote }}",
            "TunnelName"   : "{{ tunnel_name | quote }}",
            "TunnelSecret" : "{{ tunnel_secret | quote }}"
          }
        mode: "0440"

    - name: Install the tunnel as a systemd service.
      block:
        - name: Install the tunnel as a systemd service
          ansible.builtin.shell: |
            sudo cloudflared service install
          register: my_output # <- Registers the command output.
          changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
      rescue:
        - name: Print when errors
          ansible.builtin.debug:
            msg: "service installation failed, already installed?"

    - name: Increase the maximum receive buffer size.
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: 2500000
        state: present
        reload: true

    - name: Start the tunnel.
      ansible.builtin.service:
        name: cloudflared
        state: restarted
